import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

_model = SentenceTransformer("all-MiniLM-L6-v2")
_EMBEDDING_DIM = 384  # all-MiniLM-L6-v2 always produces 384-number vectors


class VectorStore:
    """
    A vector store for semantic similarity search of patient medical summaries.
    
    Uses FAISS (Facebook AI Similarity Search) for efficient nearest neighbor search
    on embeddings generated by the SentenceTransformer model (all-MiniLM-L6-v2).
    """
    
    def __init__(self):
        """
        Initialize the vector store with an empty FAISS index.
        
        Creates a flat L2 distance-based index with dimension matching the 
        embedding model's output size (384 for all-MiniLM-L6-v2).
        """
        self.index = faiss.IndexFlatL2(_EMBEDDING_DIM)
        self.texts: list[str] = []

    def add_summary(self, patient_id: int, text: str) -> None:
        """
        Add a patient medical summary to the vector store.
        
        Encodes the text using the SentenceTransformer model and adds the
        resulting embedding to the FAISS index while storing the original text.
        
        Args:
            patient_id: The unique identifier for the patient (currently stored
                       as metadata but not directly indexed).
            text: The patient medical summary or clinical note to add.
        """
        vector = _model.encode([text])
        self.index.add(np.array(vector))
        self.texts.append(text)

    def retrieve_similar(self, query: str, k: int = 3) -> list[str]:
        """
        Retrieve the k most similar summaries to a given query.
        
        Encodes the query text and performs a nearest neighbor search in the
        FAISS index using L2 distance metric. Returns the k most similar summaries
        or fewer if the store contains fewer than k entries.
        
        Args:
            query: The query text to find similar summaries for.
            k: The number of nearest neighbors to retrieve (default: 3).
               Automatically capped to the number of available summaries.
        
        Returns:
            A list of the k most similar text summaries from the store,
            ordered by similarity (most similar first).
        """
        if len(self.texts) == 0:
            return []
        k = min(k, len(self.texts))  # don't ask for more results than we have
        query_vector = _model.encode([query])
        distances, indices = self.index.search(np.array(query_vector), k)
        return [self.texts[i] for i in indices[0]]
